### ISSUE TITLE
test mDNS for discovery

### ISSUE THREAD

**Issue by mgood** [ajbouh/substrate#40]
Making a note since I saw some discussion about discovering the substrate host's IP. We might want to try out mDNS for advertising a hostname like `substrate.local` on the local network.
Maybe a Docker image like this one would be sufficient:
https://hub.docker.com/r/ianblenke/avahi

**Comment by ajbouh** [comment]
Good suggestion, yes we should absolutely enable mdns

**Comment by mgood** [comment]
I found a pretty simple mdns-publisher container that seems to work. I ran this on the Ubuntu install since I was trying it out to have a more durable dev environment on the machine. It does need access to the host dbus socket, but maybe we can get more granular with the permissions if needed.

Ran this based on their example `compose.yaml` and can `ping substrate.local` from my MacBook:
```
services:
  mdns-publisher:
    image: baywolfstudios/mdns-publisher
    security_opt:
      - apparmor:unconfined
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    environment:
      CNAMEs: substrate.local
```
